server:
  port: ${port:8762}
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: springcloud-provider-log
  data:
    mongodb:
      host: 127.0.0.1
      database: 1708blog
      port: 27017
